// Code generated by ent, DO NOT EDIT.

package post

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the post type in the database.
	Label = "post"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLang holds the string denoting the lang field in the database.
	FieldLang = "lang"
	// FieldSlug holds the string denoting the slug field in the database.
	FieldSlug = "slug"
	// FieldOldSlugs holds the string denoting the old_slugs field in the database.
	FieldOldSlugs = "old_slugs"
	// FieldTranslationKey holds the string denoting the translation_key field in the database.
	FieldTranslationKey = "translation_key"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldCoverURL holds the string denoting the cover_url field in the database.
	FieldCoverURL = "cover_url"
	// FieldCoverAlt holds the string denoting the cover_alt field in the database.
	FieldCoverAlt = "cover_alt"
	// FieldPublishedAt holds the string denoting the published_at field in the database.
	FieldPublishedAt = "published_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldStateChangedAt holds the string denoting the state_changed_at field in the database.
	FieldStateChangedAt = "state_changed_at"
	// FieldPublishedSnapshot holds the string denoting the published_snapshot field in the database.
	FieldPublishedSnapshot = "published_snapshot"
	// Table holds the table name of the post in the database.
	Table = "posts"
)

// Columns holds all SQL columns for post fields.
var Columns = []string{
	FieldID,
	FieldLang,
	FieldSlug,
	FieldOldSlugs,
	FieldTranslationKey,
	FieldTitle,
	FieldDescription,
	FieldContent,
	FieldTags,
	FieldCoverURL,
	FieldCoverAlt,
	FieldPublishedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldStateChangedAt,
	FieldPublishedSnapshot,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultLang holds the default value on creation for the "lang" field.
	DefaultLang string
	// DefaultOldSlugs holds the default value on creation for the "old_slugs" field.
	DefaultOldSlugs []string
	// DefaultTitle holds the default value on creation for the "title" field.
	DefaultTitle string
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DefaultContent holds the default value on creation for the "content" field.
	DefaultContent string
	// DefaultTags holds the default value on creation for the "tags" field.
	DefaultTags []string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Post queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLang orders the results by the lang field.
func ByLang(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLang, opts...).ToFunc()
}

// BySlug orders the results by the slug field.
func BySlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlug, opts...).ToFunc()
}

// ByTranslationKey orders the results by the translation_key field.
func ByTranslationKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTranslationKey, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByCoverURL orders the results by the cover_url field.
func ByCoverURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCoverURL, opts...).ToFunc()
}

// ByCoverAlt orders the results by the cover_alt field.
func ByCoverAlt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCoverAlt, opts...).ToFunc()
}

// ByPublishedAt orders the results by the published_at field.
func ByPublishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByStateChangedAt orders the results by the state_changed_at field.
func ByStateChangedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStateChangedAt, opts...).ToFunc()
}
