// Code generated by ent, DO NOT EDIT.

package post

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/nachop51/nachop51/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldID, id))
}

// Lang applies equality check predicate on the "lang" field. It's identical to LangEQ.
func Lang(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldLang, v))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldSlug, v))
}

// TranslationKey applies equality check predicate on the "translation_key" field. It's identical to TranslationKeyEQ.
func TranslationKey(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldTranslationKey, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldDescription, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldContent, v))
}

// CoverURL applies equality check predicate on the "cover_url" field. It's identical to CoverURLEQ.
func CoverURL(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldCoverURL, v))
}

// CoverAlt applies equality check predicate on the "cover_alt" field. It's identical to CoverAltEQ.
func CoverAlt(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldCoverAlt, v))
}

// PublishedAt applies equality check predicate on the "published_at" field. It's identical to PublishedAtEQ.
func PublishedAt(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldPublishedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldUpdatedAt, v))
}

// StateChangedAt applies equality check predicate on the "state_changed_at" field. It's identical to StateChangedAtEQ.
func StateChangedAt(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldStateChangedAt, v))
}

// LangEQ applies the EQ predicate on the "lang" field.
func LangEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldLang, v))
}

// LangNEQ applies the NEQ predicate on the "lang" field.
func LangNEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldLang, v))
}

// LangIn applies the In predicate on the "lang" field.
func LangIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldLang, vs...))
}

// LangNotIn applies the NotIn predicate on the "lang" field.
func LangNotIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldLang, vs...))
}

// LangGT applies the GT predicate on the "lang" field.
func LangGT(v string) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldLang, v))
}

// LangGTE applies the GTE predicate on the "lang" field.
func LangGTE(v string) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldLang, v))
}

// LangLT applies the LT predicate on the "lang" field.
func LangLT(v string) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldLang, v))
}

// LangLTE applies the LTE predicate on the "lang" field.
func LangLTE(v string) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldLang, v))
}

// LangContains applies the Contains predicate on the "lang" field.
func LangContains(v string) predicate.Post {
	return predicate.Post(sql.FieldContains(FieldLang, v))
}

// LangHasPrefix applies the HasPrefix predicate on the "lang" field.
func LangHasPrefix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasPrefix(FieldLang, v))
}

// LangHasSuffix applies the HasSuffix predicate on the "lang" field.
func LangHasSuffix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasSuffix(FieldLang, v))
}

// LangEqualFold applies the EqualFold predicate on the "lang" field.
func LangEqualFold(v string) predicate.Post {
	return predicate.Post(sql.FieldEqualFold(FieldLang, v))
}

// LangContainsFold applies the ContainsFold predicate on the "lang" field.
func LangContainsFold(v string) predicate.Post {
	return predicate.Post(sql.FieldContainsFold(FieldLang, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.Post {
	return predicate.Post(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.Post {
	return predicate.Post(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.Post {
	return predicate.Post(sql.FieldContainsFold(FieldSlug, v))
}

// TranslationKeyEQ applies the EQ predicate on the "translation_key" field.
func TranslationKeyEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldTranslationKey, v))
}

// TranslationKeyNEQ applies the NEQ predicate on the "translation_key" field.
func TranslationKeyNEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldTranslationKey, v))
}

// TranslationKeyIn applies the In predicate on the "translation_key" field.
func TranslationKeyIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldTranslationKey, vs...))
}

// TranslationKeyNotIn applies the NotIn predicate on the "translation_key" field.
func TranslationKeyNotIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldTranslationKey, vs...))
}

// TranslationKeyGT applies the GT predicate on the "translation_key" field.
func TranslationKeyGT(v string) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldTranslationKey, v))
}

// TranslationKeyGTE applies the GTE predicate on the "translation_key" field.
func TranslationKeyGTE(v string) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldTranslationKey, v))
}

// TranslationKeyLT applies the LT predicate on the "translation_key" field.
func TranslationKeyLT(v string) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldTranslationKey, v))
}

// TranslationKeyLTE applies the LTE predicate on the "translation_key" field.
func TranslationKeyLTE(v string) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldTranslationKey, v))
}

// TranslationKeyContains applies the Contains predicate on the "translation_key" field.
func TranslationKeyContains(v string) predicate.Post {
	return predicate.Post(sql.FieldContains(FieldTranslationKey, v))
}

// TranslationKeyHasPrefix applies the HasPrefix predicate on the "translation_key" field.
func TranslationKeyHasPrefix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasPrefix(FieldTranslationKey, v))
}

// TranslationKeyHasSuffix applies the HasSuffix predicate on the "translation_key" field.
func TranslationKeyHasSuffix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasSuffix(FieldTranslationKey, v))
}

// TranslationKeyIsNil applies the IsNil predicate on the "translation_key" field.
func TranslationKeyIsNil() predicate.Post {
	return predicate.Post(sql.FieldIsNull(FieldTranslationKey))
}

// TranslationKeyNotNil applies the NotNil predicate on the "translation_key" field.
func TranslationKeyNotNil() predicate.Post {
	return predicate.Post(sql.FieldNotNull(FieldTranslationKey))
}

// TranslationKeyEqualFold applies the EqualFold predicate on the "translation_key" field.
func TranslationKeyEqualFold(v string) predicate.Post {
	return predicate.Post(sql.FieldEqualFold(FieldTranslationKey, v))
}

// TranslationKeyContainsFold applies the ContainsFold predicate on the "translation_key" field.
func TranslationKeyContainsFold(v string) predicate.Post {
	return predicate.Post(sql.FieldContainsFold(FieldTranslationKey, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Post {
	return predicate.Post(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Post {
	return predicate.Post(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Post {
	return predicate.Post(sql.FieldContainsFold(FieldTitle, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Post {
	return predicate.Post(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Post {
	return predicate.Post(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Post {
	return predicate.Post(sql.FieldContainsFold(FieldDescription, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.Post {
	return predicate.Post(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.Post {
	return predicate.Post(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.Post {
	return predicate.Post(sql.FieldContainsFold(FieldContent, v))
}

// CoverURLEQ applies the EQ predicate on the "cover_url" field.
func CoverURLEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldCoverURL, v))
}

// CoverURLNEQ applies the NEQ predicate on the "cover_url" field.
func CoverURLNEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldCoverURL, v))
}

// CoverURLIn applies the In predicate on the "cover_url" field.
func CoverURLIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldCoverURL, vs...))
}

// CoverURLNotIn applies the NotIn predicate on the "cover_url" field.
func CoverURLNotIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldCoverURL, vs...))
}

// CoverURLGT applies the GT predicate on the "cover_url" field.
func CoverURLGT(v string) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldCoverURL, v))
}

// CoverURLGTE applies the GTE predicate on the "cover_url" field.
func CoverURLGTE(v string) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldCoverURL, v))
}

// CoverURLLT applies the LT predicate on the "cover_url" field.
func CoverURLLT(v string) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldCoverURL, v))
}

// CoverURLLTE applies the LTE predicate on the "cover_url" field.
func CoverURLLTE(v string) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldCoverURL, v))
}

// CoverURLContains applies the Contains predicate on the "cover_url" field.
func CoverURLContains(v string) predicate.Post {
	return predicate.Post(sql.FieldContains(FieldCoverURL, v))
}

// CoverURLHasPrefix applies the HasPrefix predicate on the "cover_url" field.
func CoverURLHasPrefix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasPrefix(FieldCoverURL, v))
}

// CoverURLHasSuffix applies the HasSuffix predicate on the "cover_url" field.
func CoverURLHasSuffix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasSuffix(FieldCoverURL, v))
}

// CoverURLIsNil applies the IsNil predicate on the "cover_url" field.
func CoverURLIsNil() predicate.Post {
	return predicate.Post(sql.FieldIsNull(FieldCoverURL))
}

// CoverURLNotNil applies the NotNil predicate on the "cover_url" field.
func CoverURLNotNil() predicate.Post {
	return predicate.Post(sql.FieldNotNull(FieldCoverURL))
}

// CoverURLEqualFold applies the EqualFold predicate on the "cover_url" field.
func CoverURLEqualFold(v string) predicate.Post {
	return predicate.Post(sql.FieldEqualFold(FieldCoverURL, v))
}

// CoverURLContainsFold applies the ContainsFold predicate on the "cover_url" field.
func CoverURLContainsFold(v string) predicate.Post {
	return predicate.Post(sql.FieldContainsFold(FieldCoverURL, v))
}

// CoverAltEQ applies the EQ predicate on the "cover_alt" field.
func CoverAltEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldCoverAlt, v))
}

// CoverAltNEQ applies the NEQ predicate on the "cover_alt" field.
func CoverAltNEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldCoverAlt, v))
}

// CoverAltIn applies the In predicate on the "cover_alt" field.
func CoverAltIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldCoverAlt, vs...))
}

// CoverAltNotIn applies the NotIn predicate on the "cover_alt" field.
func CoverAltNotIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldCoverAlt, vs...))
}

// CoverAltGT applies the GT predicate on the "cover_alt" field.
func CoverAltGT(v string) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldCoverAlt, v))
}

// CoverAltGTE applies the GTE predicate on the "cover_alt" field.
func CoverAltGTE(v string) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldCoverAlt, v))
}

// CoverAltLT applies the LT predicate on the "cover_alt" field.
func CoverAltLT(v string) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldCoverAlt, v))
}

// CoverAltLTE applies the LTE predicate on the "cover_alt" field.
func CoverAltLTE(v string) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldCoverAlt, v))
}

// CoverAltContains applies the Contains predicate on the "cover_alt" field.
func CoverAltContains(v string) predicate.Post {
	return predicate.Post(sql.FieldContains(FieldCoverAlt, v))
}

// CoverAltHasPrefix applies the HasPrefix predicate on the "cover_alt" field.
func CoverAltHasPrefix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasPrefix(FieldCoverAlt, v))
}

// CoverAltHasSuffix applies the HasSuffix predicate on the "cover_alt" field.
func CoverAltHasSuffix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasSuffix(FieldCoverAlt, v))
}

// CoverAltIsNil applies the IsNil predicate on the "cover_alt" field.
func CoverAltIsNil() predicate.Post {
	return predicate.Post(sql.FieldIsNull(FieldCoverAlt))
}

// CoverAltNotNil applies the NotNil predicate on the "cover_alt" field.
func CoverAltNotNil() predicate.Post {
	return predicate.Post(sql.FieldNotNull(FieldCoverAlt))
}

// CoverAltEqualFold applies the EqualFold predicate on the "cover_alt" field.
func CoverAltEqualFold(v string) predicate.Post {
	return predicate.Post(sql.FieldEqualFold(FieldCoverAlt, v))
}

// CoverAltContainsFold applies the ContainsFold predicate on the "cover_alt" field.
func CoverAltContainsFold(v string) predicate.Post {
	return predicate.Post(sql.FieldContainsFold(FieldCoverAlt, v))
}

// PublishedAtEQ applies the EQ predicate on the "published_at" field.
func PublishedAtEQ(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldPublishedAt, v))
}

// PublishedAtNEQ applies the NEQ predicate on the "published_at" field.
func PublishedAtNEQ(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldPublishedAt, v))
}

// PublishedAtIn applies the In predicate on the "published_at" field.
func PublishedAtIn(vs ...time.Time) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldPublishedAt, vs...))
}

// PublishedAtNotIn applies the NotIn predicate on the "published_at" field.
func PublishedAtNotIn(vs ...time.Time) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldPublishedAt, vs...))
}

// PublishedAtGT applies the GT predicate on the "published_at" field.
func PublishedAtGT(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldPublishedAt, v))
}

// PublishedAtGTE applies the GTE predicate on the "published_at" field.
func PublishedAtGTE(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldPublishedAt, v))
}

// PublishedAtLT applies the LT predicate on the "published_at" field.
func PublishedAtLT(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldPublishedAt, v))
}

// PublishedAtLTE applies the LTE predicate on the "published_at" field.
func PublishedAtLTE(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldPublishedAt, v))
}

// PublishedAtIsNil applies the IsNil predicate on the "published_at" field.
func PublishedAtIsNil() predicate.Post {
	return predicate.Post(sql.FieldIsNull(FieldPublishedAt))
}

// PublishedAtNotNil applies the NotNil predicate on the "published_at" field.
func PublishedAtNotNil() predicate.Post {
	return predicate.Post(sql.FieldNotNull(FieldPublishedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldUpdatedAt, v))
}

// StateChangedAtEQ applies the EQ predicate on the "state_changed_at" field.
func StateChangedAtEQ(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldStateChangedAt, v))
}

// StateChangedAtNEQ applies the NEQ predicate on the "state_changed_at" field.
func StateChangedAtNEQ(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldStateChangedAt, v))
}

// StateChangedAtIn applies the In predicate on the "state_changed_at" field.
func StateChangedAtIn(vs ...time.Time) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldStateChangedAt, vs...))
}

// StateChangedAtNotIn applies the NotIn predicate on the "state_changed_at" field.
func StateChangedAtNotIn(vs ...time.Time) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldStateChangedAt, vs...))
}

// StateChangedAtGT applies the GT predicate on the "state_changed_at" field.
func StateChangedAtGT(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldStateChangedAt, v))
}

// StateChangedAtGTE applies the GTE predicate on the "state_changed_at" field.
func StateChangedAtGTE(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldStateChangedAt, v))
}

// StateChangedAtLT applies the LT predicate on the "state_changed_at" field.
func StateChangedAtLT(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldStateChangedAt, v))
}

// StateChangedAtLTE applies the LTE predicate on the "state_changed_at" field.
func StateChangedAtLTE(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldStateChangedAt, v))
}

// StateChangedAtIsNil applies the IsNil predicate on the "state_changed_at" field.
func StateChangedAtIsNil() predicate.Post {
	return predicate.Post(sql.FieldIsNull(FieldStateChangedAt))
}

// StateChangedAtNotNil applies the NotNil predicate on the "state_changed_at" field.
func StateChangedAtNotNil() predicate.Post {
	return predicate.Post(sql.FieldNotNull(FieldStateChangedAt))
}

// PublishedSnapshotIsNil applies the IsNil predicate on the "published_snapshot" field.
func PublishedSnapshotIsNil() predicate.Post {
	return predicate.Post(sql.FieldIsNull(FieldPublishedSnapshot))
}

// PublishedSnapshotNotNil applies the NotNil predicate on the "published_snapshot" field.
func PublishedSnapshotNotNil() predicate.Post {
	return predicate.Post(sql.FieldNotNull(FieldPublishedSnapshot))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Post) predicate.Post {
	return predicate.Post(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Post) predicate.Post {
	return predicate.Post(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Post) predicate.Post {
	return predicate.Post(sql.NotPredicates(p))
}
