// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Asset is the predicate function for asset builders.
type Asset func(*sql.Selector)

// Deployment is the predicate function for deployment builders.
type Deployment func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)
