// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AssetsColumns holds the columns for the "assets" table.
	AssetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "key", Type: field.TypeString},
		{Name: "url", Type: field.TypeString},
		{Name: "original_name", Type: field.TypeString, Default: ""},
		{Name: "content_type", Type: field.TypeString},
		{Name: "size", Type: field.TypeInt64},
		{Name: "created_at", Type: field.TypeTime},
	}
	// AssetsTable holds the schema information for the "assets" table.
	AssetsTable = &schema.Table{
		Name:       "assets",
		Columns:    AssetsColumns,
		PrimaryKey: []*schema.Column{AssetsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "asset_created_at",
				Unique:  false,
				Columns: []*schema.Column{AssetsColumns[6]},
			},
		},
	}
	// DeploymentsColumns holds the columns for the "deployments" table.
	DeploymentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "ok", Type: field.TypeBool, Default: false},
		{Name: "error", Type: field.TypeString, Size: 2147483647, Default: ""},
	}
	// DeploymentsTable holds the schema information for the "deployments" table.
	DeploymentsTable = &schema.Table{
		Name:       "deployments",
		Columns:    DeploymentsColumns,
		PrimaryKey: []*schema.Column{DeploymentsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "deployment_created_at",
				Unique:  false,
				Columns: []*schema.Column{DeploymentsColumns[1]},
			},
		},
	}
	// PostsColumns holds the columns for the "posts" table.
	PostsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "lang", Type: field.TypeString, Default: "en"},
		{Name: "slug", Type: field.TypeString},
		{Name: "old_slugs", Type: field.TypeJSON},
		{Name: "translation_key", Type: field.TypeString, Nullable: true},
		{Name: "title", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "description", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "content", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "tags", Type: field.TypeJSON},
		{Name: "cover_url", Type: field.TypeString, Nullable: true},
		{Name: "cover_alt", Type: field.TypeString, Nullable: true},
		{Name: "published_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "state_changed_at", Type: field.TypeTime, Nullable: true},
		{Name: "published_snapshot", Type: field.TypeJSON, Nullable: true},
	}
	// PostsTable holds the schema information for the "posts" table.
	PostsTable = &schema.Table{
		Name:       "posts",
		Columns:    PostsColumns,
		PrimaryKey: []*schema.Column{PostsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "post_lang_slug",
				Unique:  true,
				Columns: []*schema.Column{PostsColumns[1], PostsColumns[2]},
			},
			{
				Name:    "post_translation_key_lang",
				Unique:  true,
				Columns: []*schema.Column{PostsColumns[4], PostsColumns[1]},
				Annotation: &entsql.IndexAnnotation{
					Where: "translation_key IS NOT NULL",
				},
			},
			{
				Name:    "post_published_at",
				Unique:  false,
				Columns: []*schema.Column{PostsColumns[11]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AssetsTable,
		DeploymentsTable,
		PostsTable,
	}
)

func init() {
	PostsTable.Annotation = &entsql.Annotation{}
	PostsTable.Annotation.Checks = map[string]string{
		"lang_valid":  "lang IN ('en', 'es')",
		"publishable": "published_at IS NULL OR (title <> '' AND description <> '' AND slug <> '' AND content <> '')",
	}
}
