// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nachop51/nachop51/ent/deployment"
	"github.com/nachop51/nachop51/ent/predicate"
)

// DeploymentUpdate is the builder for updating Deployment entities.
type DeploymentUpdate struct {
	config
	hooks    []Hook
	mutation *DeploymentMutation
}

// Where appends a list predicates to the DeploymentUpdate builder.
func (_u *DeploymentUpdate) Where(ps ...predicate.Deployment) *DeploymentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOk sets the "ok" field.
func (_u *DeploymentUpdate) SetOk(v bool) *DeploymentUpdate {
	_u.mutation.SetOk(v)
	return _u
}

// SetNillableOk sets the "ok" field if the given value is not nil.
func (_u *DeploymentUpdate) SetNillableOk(v *bool) *DeploymentUpdate {
	if v != nil {
		_u.SetOk(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *DeploymentUpdate) SetError(v string) *DeploymentUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *DeploymentUpdate) SetNillableError(v *string) *DeploymentUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// Mutation returns the DeploymentMutation object of the builder.
func (_u *DeploymentUpdate) Mutation() *DeploymentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeploymentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeploymentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeploymentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeploymentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *DeploymentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(deployment.Table, deployment.Columns, sqlgraph.NewFieldSpec(deployment.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Ok(); ok {
		_spec.SetField(deployment.FieldOk, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(deployment.FieldError, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deployment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeploymentUpdateOne is the builder for updating a single Deployment entity.
type DeploymentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeploymentMutation
}

// SetOk sets the "ok" field.
func (_u *DeploymentUpdateOne) SetOk(v bool) *DeploymentUpdateOne {
	_u.mutation.SetOk(v)
	return _u
}

// SetNillableOk sets the "ok" field if the given value is not nil.
func (_u *DeploymentUpdateOne) SetNillableOk(v *bool) *DeploymentUpdateOne {
	if v != nil {
		_u.SetOk(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *DeploymentUpdateOne) SetError(v string) *DeploymentUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *DeploymentUpdateOne) SetNillableError(v *string) *DeploymentUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// Mutation returns the DeploymentMutation object of the builder.
func (_u *DeploymentUpdateOne) Mutation() *DeploymentMutation {
	return _u.mutation
}

// Where appends a list predicates to the DeploymentUpdate builder.
func (_u *DeploymentUpdateOne) Where(ps ...predicate.Deployment) *DeploymentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeploymentUpdateOne) Select(field string, fields ...string) *DeploymentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Deployment entity.
func (_u *DeploymentUpdateOne) Save(ctx context.Context) (*Deployment, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeploymentUpdateOne) SaveX(ctx context.Context) *Deployment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeploymentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeploymentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *DeploymentUpdateOne) sqlSave(ctx context.Context) (_node *Deployment, err error) {
	_spec := sqlgraph.NewUpdateSpec(deployment.Table, deployment.Columns, sqlgraph.NewFieldSpec(deployment.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Deployment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deployment.FieldID)
		for _, f := range fields {
			if !deployment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != deployment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Ok(); ok {
		_spec.SetField(deployment.FieldOk, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(deployment.FieldError, field.TypeString, value)
	}
	_node = &Deployment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deployment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
