// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/nachop51/nachop51/ent/post"
	"github.com/nachop51/nachop51/internal/model"
)

// PostCreate is the builder for creating a Post entity.
type PostCreate struct {
	config
	mutation *PostMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetLang sets the "lang" field.
func (_c *PostCreate) SetLang(v string) *PostCreate {
	_c.mutation.SetLang(v)
	return _c
}

// SetSlug sets the "slug" field.
func (_c *PostCreate) SetSlug(v string) *PostCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetOldSlugs sets the "old_slugs" field.
func (_c *PostCreate) SetOldSlugs(v []string) *PostCreate {
	_c.mutation.SetOldSlugs(v)
	return _c
}

// SetTranslationKey sets the "translation_key" field.
func (_c *PostCreate) SetTranslationKey(v string) *PostCreate {
	_c.mutation.SetTranslationKey(v)
	return _c
}

// SetNillableTranslationKey sets the "translation_key" field if the given value is not nil.
func (_c *PostCreate) SetNillableTranslationKey(v *string) *PostCreate {
	if v != nil {
		_c.SetTranslationKey(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *PostCreate) SetTitle(v string) *PostCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *PostCreate) SetNillableTitle(v *string) *PostCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *PostCreate) SetDescription(v string) *PostCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *PostCreate) SetNillableDescription(v *string) *PostCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *PostCreate) SetContent(v string) *PostCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_c *PostCreate) SetNillableContent(v *string) *PostCreate {
	if v != nil {
		_c.SetContent(*v)
	}
	return _c
}

// SetTags sets the "tags" field.
func (_c *PostCreate) SetTags(v []string) *PostCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetCoverURL sets the "cover_url" field.
func (_c *PostCreate) SetCoverURL(v string) *PostCreate {
	_c.mutation.SetCoverURL(v)
	return _c
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (_c *PostCreate) SetNillableCoverURL(v *string) *PostCreate {
	if v != nil {
		_c.SetCoverURL(*v)
	}
	return _c
}

// SetCoverAlt sets the "cover_alt" field.
func (_c *PostCreate) SetCoverAlt(v string) *PostCreate {
	_c.mutation.SetCoverAlt(v)
	return _c
}

// SetNillableCoverAlt sets the "cover_alt" field if the given value is not nil.
func (_c *PostCreate) SetNillableCoverAlt(v *string) *PostCreate {
	if v != nil {
		_c.SetCoverAlt(*v)
	}
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *PostCreate) SetPublishedAt(v time.Time) *PostCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_c *PostCreate) SetNillablePublishedAt(v *time.Time) *PostCreate {
	if v != nil {
		_c.SetPublishedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PostCreate) SetCreatedAt(v time.Time) *PostCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PostCreate) SetNillableCreatedAt(v *time.Time) *PostCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PostCreate) SetUpdatedAt(v time.Time) *PostCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PostCreate) SetNillableUpdatedAt(v *time.Time) *PostCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPublishedSnapshot sets the "published_snapshot" field.
func (_c *PostCreate) SetPublishedSnapshot(v *model.Snapshot) *PostCreate {
	_c.mutation.SetPublishedSnapshot(v)
	return _c
}

// SetID sets the "id" field.
func (_c *PostCreate) SetID(v uuid.UUID) *PostCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PostCreate) SetNillableID(v *uuid.UUID) *PostCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the PostMutation object of the builder.
func (_c *PostCreate) Mutation() *PostMutation {
	return _c.mutation
}

// Save creates the Post in the database.
func (_c *PostCreate) Save(ctx context.Context) (*Post, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PostCreate) SaveX(ctx context.Context) *Post {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PostCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PostCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PostCreate) defaults() {
	if _, ok := _c.mutation.OldSlugs(); !ok {
		v := post.DefaultOldSlugs
		_c.mutation.SetOldSlugs(v)
	}
	if _, ok := _c.mutation.Title(); !ok {
		v := post.DefaultTitle
		_c.mutation.SetTitle(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := post.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Content(); !ok {
		v := post.DefaultContent
		_c.mutation.SetContent(v)
	}
	if _, ok := _c.mutation.Tags(); !ok {
		v := post.DefaultTags
		_c.mutation.SetTags(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := post.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := post.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := post.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PostCreate) check() error {
	if _, ok := _c.mutation.Lang(); !ok {
		return &ValidationError{Name: "lang", err: errors.New(`ent: missing required field "Post.lang"`)}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Post.slug"`)}
	}
	if _, ok := _c.mutation.OldSlugs(); !ok {
		return &ValidationError{Name: "old_slugs", err: errors.New(`ent: missing required field "Post.old_slugs"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Post.title"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Post.description"`)}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Post.content"`)}
	}
	if _, ok := _c.mutation.Tags(); !ok {
		return &ValidationError{Name: "tags", err: errors.New(`ent: missing required field "Post.tags"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Post.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Post.updated_at"`)}
	}
	return nil
}

func (_c *PostCreate) sqlSave(ctx context.Context) (*Post, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PostCreate) createSpec() (*Post, *sqlgraph.CreateSpec) {
	var (
		_node = &Post{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(post.Table, sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Lang(); ok {
		_spec.SetField(post.FieldLang, field.TypeString, value)
		_node.Lang = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(post.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.OldSlugs(); ok {
		_spec.SetField(post.FieldOldSlugs, field.TypeJSON, value)
		_node.OldSlugs = value
	}
	if value, ok := _c.mutation.TranslationKey(); ok {
		_spec.SetField(post.FieldTranslationKey, field.TypeString, value)
		_node.TranslationKey = &value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(post.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(post.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(post.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(post.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.CoverURL(); ok {
		_spec.SetField(post.FieldCoverURL, field.TypeString, value)
		_node.CoverURL = &value
	}
	if value, ok := _c.mutation.CoverAlt(); ok {
		_spec.SetField(post.FieldCoverAlt, field.TypeString, value)
		_node.CoverAlt = &value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(post.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(post.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(post.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.PublishedSnapshot(); ok {
		_spec.SetField(post.FieldPublishedSnapshot, field.TypeJSON, value)
		_node.PublishedSnapshot = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Post.Create().
//		SetLang(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PostUpsert) {
//			SetLang(v+v).
//		}).
//		Exec(ctx)
func (_c *PostCreate) OnConflict(opts ...sql.ConflictOption) *PostUpsertOne {
	_c.conflict = opts
	return &PostUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Post.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PostCreate) OnConflictColumns(columns ...string) *PostUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PostUpsertOne{
		create: _c,
	}
}

type (
	// PostUpsertOne is the builder for "upsert"-ing
	//  one Post node.
	PostUpsertOne struct {
		create *PostCreate
	}

	// PostUpsert is the "OnConflict" setter.
	PostUpsert struct {
		*sql.UpdateSet
	}
)

// SetSlug sets the "slug" field.
func (u *PostUpsert) SetSlug(v string) *PostUpsert {
	u.Set(post.FieldSlug, v)
	return u
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *PostUpsert) UpdateSlug() *PostUpsert {
	u.SetExcluded(post.FieldSlug)
	return u
}

// SetOldSlugs sets the "old_slugs" field.
func (u *PostUpsert) SetOldSlugs(v []string) *PostUpsert {
	u.Set(post.FieldOldSlugs, v)
	return u
}

// UpdateOldSlugs sets the "old_slugs" field to the value that was provided on create.
func (u *PostUpsert) UpdateOldSlugs() *PostUpsert {
	u.SetExcluded(post.FieldOldSlugs)
	return u
}

// SetTranslationKey sets the "translation_key" field.
func (u *PostUpsert) SetTranslationKey(v string) *PostUpsert {
	u.Set(post.FieldTranslationKey, v)
	return u
}

// UpdateTranslationKey sets the "translation_key" field to the value that was provided on create.
func (u *PostUpsert) UpdateTranslationKey() *PostUpsert {
	u.SetExcluded(post.FieldTranslationKey)
	return u
}

// ClearTranslationKey clears the value of the "translation_key" field.
func (u *PostUpsert) ClearTranslationKey() *PostUpsert {
	u.SetNull(post.FieldTranslationKey)
	return u
}

// SetTitle sets the "title" field.
func (u *PostUpsert) SetTitle(v string) *PostUpsert {
	u.Set(post.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *PostUpsert) UpdateTitle() *PostUpsert {
	u.SetExcluded(post.FieldTitle)
	return u
}

// SetDescription sets the "description" field.
func (u *PostUpsert) SetDescription(v string) *PostUpsert {
	u.Set(post.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *PostUpsert) UpdateDescription() *PostUpsert {
	u.SetExcluded(post.FieldDescription)
	return u
}

// SetContent sets the "content" field.
func (u *PostUpsert) SetContent(v string) *PostUpsert {
	u.Set(post.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *PostUpsert) UpdateContent() *PostUpsert {
	u.SetExcluded(post.FieldContent)
	return u
}

// SetTags sets the "tags" field.
func (u *PostUpsert) SetTags(v []string) *PostUpsert {
	u.Set(post.FieldTags, v)
	return u
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *PostUpsert) UpdateTags() *PostUpsert {
	u.SetExcluded(post.FieldTags)
	return u
}

// SetCoverURL sets the "cover_url" field.
func (u *PostUpsert) SetCoverURL(v string) *PostUpsert {
	u.Set(post.FieldCoverURL, v)
	return u
}

// UpdateCoverURL sets the "cover_url" field to the value that was provided on create.
func (u *PostUpsert) UpdateCoverURL() *PostUpsert {
	u.SetExcluded(post.FieldCoverURL)
	return u
}

// ClearCoverURL clears the value of the "cover_url" field.
func (u *PostUpsert) ClearCoverURL() *PostUpsert {
	u.SetNull(post.FieldCoverURL)
	return u
}

// SetCoverAlt sets the "cover_alt" field.
func (u *PostUpsert) SetCoverAlt(v string) *PostUpsert {
	u.Set(post.FieldCoverAlt, v)
	return u
}

// UpdateCoverAlt sets the "cover_alt" field to the value that was provided on create.
func (u *PostUpsert) UpdateCoverAlt() *PostUpsert {
	u.SetExcluded(post.FieldCoverAlt)
	return u
}

// ClearCoverAlt clears the value of the "cover_alt" field.
func (u *PostUpsert) ClearCoverAlt() *PostUpsert {
	u.SetNull(post.FieldCoverAlt)
	return u
}

// SetPublishedAt sets the "published_at" field.
func (u *PostUpsert) SetPublishedAt(v time.Time) *PostUpsert {
	u.Set(post.FieldPublishedAt, v)
	return u
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *PostUpsert) UpdatePublishedAt() *PostUpsert {
	u.SetExcluded(post.FieldPublishedAt)
	return u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *PostUpsert) ClearPublishedAt() *PostUpsert {
	u.SetNull(post.FieldPublishedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PostUpsert) SetUpdatedAt(v time.Time) *PostUpsert {
	u.Set(post.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PostUpsert) UpdateUpdatedAt() *PostUpsert {
	u.SetExcluded(post.FieldUpdatedAt)
	return u
}

// SetPublishedSnapshot sets the "published_snapshot" field.
func (u *PostUpsert) SetPublishedSnapshot(v *model.Snapshot) *PostUpsert {
	u.Set(post.FieldPublishedSnapshot, v)
	return u
}

// UpdatePublishedSnapshot sets the "published_snapshot" field to the value that was provided on create.
func (u *PostUpsert) UpdatePublishedSnapshot() *PostUpsert {
	u.SetExcluded(post.FieldPublishedSnapshot)
	return u
}

// ClearPublishedSnapshot clears the value of the "published_snapshot" field.
func (u *PostUpsert) ClearPublishedSnapshot() *PostUpsert {
	u.SetNull(post.FieldPublishedSnapshot)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Post.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(post.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PostUpsertOne) UpdateNewValues() *PostUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(post.FieldID)
		}
		if _, exists := u.create.mutation.Lang(); exists {
			s.SetIgnore(post.FieldLang)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(post.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Post.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PostUpsertOne) Ignore() *PostUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PostUpsertOne) DoNothing() *PostUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PostCreate.OnConflict
// documentation for more info.
func (u *PostUpsertOne) Update(set func(*PostUpsert)) *PostUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PostUpsert{UpdateSet: update})
	}))
	return u
}

// SetSlug sets the "slug" field.
func (u *PostUpsertOne) SetSlug(v string) *PostUpsertOne {
	return u.Update(func(s *PostUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *PostUpsertOne) UpdateSlug() *PostUpsertOne {
	return u.Update(func(s *PostUpsert) {
		s.UpdateSlug()
	})
}

// SetOldSlugs sets the "old_slugs" field.
func (u *PostUpsertOne) SetOldSlugs(v []string) *PostUpsertOne {
	return u.Update(func(s *PostUpsert) {
		s.SetOldSlugs(v)
	})
}

// UpdateOldSlugs sets the "old_slugs" field to the value that was provided on create.
func (u *PostUpsertOne) UpdateOldSlugs() *PostUpsertOne {
	return u.Update(func(s *PostUpsert) {
		s.UpdateOldSlugs()
	})
}

// SetTranslationKey sets the "translation_key" field.
func (u *PostUpsertOne) SetTranslationKey(v string) *PostUpsertOne {
	return u.Update(func(s *PostUpsert) {
		s.SetTranslationKey(v)
	})
}

// UpdateTranslationKey sets the "translation_key" field to the value that was provided on create.
func (u *PostUpsertOne) UpdateTranslationKey() *PostUpsertOne {
	return u.Update(func(s *PostUpsert) {
		s.UpdateTranslationKey()
	})
}

// ClearTranslationKey clears the value of the "translation_key" field.
func (u *PostUpsertOne) ClearTranslationKey() *PostUpsertOne {
	return u.Update(func(s *PostUpsert) {
		s.ClearTranslationKey()
	})
}

// SetTitle sets the "title" field.
func (u *PostUpsertOne) SetTitle(v string) *PostUpsertOne {
	return u.Update(func(s *PostUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *PostUpsertOne) UpdateTitle() *PostUpsertOne {
	return u.Update(func(s *PostUpsert) {
		s.UpdateTitle()
	})
}

// SetDescription sets the "description" field.
func (u *PostUpsertOne) SetDescription(v string) *PostUpsertOne {
	return u.Update(func(s *PostUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *PostUpsertOne) UpdateDescription() *PostUpsertOne {
	return u.Update(func(s *PostUpsert) {
		s.UpdateDescription()
	})
}

// SetContent sets the "content" field.
func (u *PostUpsertOne) SetContent(v string) *PostUpsertOne {
	return u.Update(func(s *PostUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *PostUpsertOne) UpdateContent() *PostUpsertOne {
	return u.Update(func(s *PostUpsert) {
		s.UpdateContent()
	})
}

// SetTags sets the "tags" field.
func (u *PostUpsertOne) SetTags(v []string) *PostUpsertOne {
	return u.Update(func(s *PostUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *PostUpsertOne) UpdateTags() *PostUpsertOne {
	return u.Update(func(s *PostUpsert) {
		s.UpdateTags()
	})
}

// SetCoverURL sets the "cover_url" field.
func (u *PostUpsertOne) SetCoverURL(v string) *PostUpsertOne {
	return u.Update(func(s *PostUpsert) {
		s.SetCoverURL(v)
	})
}

// UpdateCoverURL sets the "cover_url" field to the value that was provided on create.
func (u *PostUpsertOne) UpdateCoverURL() *PostUpsertOne {
	return u.Update(func(s *PostUpsert) {
		s.UpdateCoverURL()
	})
}

// ClearCoverURL clears the value of the "cover_url" field.
func (u *PostUpsertOne) ClearCoverURL() *PostUpsertOne {
	return u.Update(func(s *PostUpsert) {
		s.ClearCoverURL()
	})
}

// SetCoverAlt sets the "cover_alt" field.
func (u *PostUpsertOne) SetCoverAlt(v string) *PostUpsertOne {
	return u.Update(func(s *PostUpsert) {
		s.SetCoverAlt(v)
	})
}

// UpdateCoverAlt sets the "cover_alt" field to the value that was provided on create.
func (u *PostUpsertOne) UpdateCoverAlt() *PostUpsertOne {
	return u.Update(func(s *PostUpsert) {
		s.UpdateCoverAlt()
	})
}

// ClearCoverAlt clears the value of the "cover_alt" field.
func (u *PostUpsertOne) ClearCoverAlt() *PostUpsertOne {
	return u.Update(func(s *PostUpsert) {
		s.ClearCoverAlt()
	})
}

// SetPublishedAt sets the "published_at" field.
func (u *PostUpsertOne) SetPublishedAt(v time.Time) *PostUpsertOne {
	return u.Update(func(s *PostUpsert) {
		s.SetPublishedAt(v)
	})
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *PostUpsertOne) UpdatePublishedAt() *PostUpsertOne {
	return u.Update(func(s *PostUpsert) {
		s.UpdatePublishedAt()
	})
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *PostUpsertOne) ClearPublishedAt() *PostUpsertOne {
	return u.Update(func(s *PostUpsert) {
		s.ClearPublishedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PostUpsertOne) SetUpdatedAt(v time.Time) *PostUpsertOne {
	return u.Update(func(s *PostUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PostUpsertOne) UpdateUpdatedAt() *PostUpsertOne {
	return u.Update(func(s *PostUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPublishedSnapshot sets the "published_snapshot" field.
func (u *PostUpsertOne) SetPublishedSnapshot(v *model.Snapshot) *PostUpsertOne {
	return u.Update(func(s *PostUpsert) {
		s.SetPublishedSnapshot(v)
	})
}

// UpdatePublishedSnapshot sets the "published_snapshot" field to the value that was provided on create.
func (u *PostUpsertOne) UpdatePublishedSnapshot() *PostUpsertOne {
	return u.Update(func(s *PostUpsert) {
		s.UpdatePublishedSnapshot()
	})
}

// ClearPublishedSnapshot clears the value of the "published_snapshot" field.
func (u *PostUpsertOne) ClearPublishedSnapshot() *PostUpsertOne {
	return u.Update(func(s *PostUpsert) {
		s.ClearPublishedSnapshot()
	})
}

// Exec executes the query.
func (u *PostUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PostCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PostUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PostUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: PostUpsertOne.ID is not supported by MySQL driver. Use PostUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PostUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PostCreateBulk is the builder for creating many Post entities in bulk.
type PostCreateBulk struct {
	config
	err      error
	builders []*PostCreate
	conflict []sql.ConflictOption
}

// Save creates the Post entities in the database.
func (_c *PostCreateBulk) Save(ctx context.Context) ([]*Post, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Post, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PostMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PostCreateBulk) SaveX(ctx context.Context) []*Post {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PostCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PostCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Post.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PostUpsert) {
//			SetLang(v+v).
//		}).
//		Exec(ctx)
func (_c *PostCreateBulk) OnConflict(opts ...sql.ConflictOption) *PostUpsertBulk {
	_c.conflict = opts
	return &PostUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Post.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PostCreateBulk) OnConflictColumns(columns ...string) *PostUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PostUpsertBulk{
		create: _c,
	}
}

// PostUpsertBulk is the builder for "upsert"-ing
// a bulk of Post nodes.
type PostUpsertBulk struct {
	create *PostCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Post.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(post.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PostUpsertBulk) UpdateNewValues() *PostUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(post.FieldID)
			}
			if _, exists := b.mutation.Lang(); exists {
				s.SetIgnore(post.FieldLang)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(post.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Post.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PostUpsertBulk) Ignore() *PostUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PostUpsertBulk) DoNothing() *PostUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PostCreateBulk.OnConflict
// documentation for more info.
func (u *PostUpsertBulk) Update(set func(*PostUpsert)) *PostUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PostUpsert{UpdateSet: update})
	}))
	return u
}

// SetSlug sets the "slug" field.
func (u *PostUpsertBulk) SetSlug(v string) *PostUpsertBulk {
	return u.Update(func(s *PostUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *PostUpsertBulk) UpdateSlug() *PostUpsertBulk {
	return u.Update(func(s *PostUpsert) {
		s.UpdateSlug()
	})
}

// SetOldSlugs sets the "old_slugs" field.
func (u *PostUpsertBulk) SetOldSlugs(v []string) *PostUpsertBulk {
	return u.Update(func(s *PostUpsert) {
		s.SetOldSlugs(v)
	})
}

// UpdateOldSlugs sets the "old_slugs" field to the value that was provided on create.
func (u *PostUpsertBulk) UpdateOldSlugs() *PostUpsertBulk {
	return u.Update(func(s *PostUpsert) {
		s.UpdateOldSlugs()
	})
}

// SetTranslationKey sets the "translation_key" field.
func (u *PostUpsertBulk) SetTranslationKey(v string) *PostUpsertBulk {
	return u.Update(func(s *PostUpsert) {
		s.SetTranslationKey(v)
	})
}

// UpdateTranslationKey sets the "translation_key" field to the value that was provided on create.
func (u *PostUpsertBulk) UpdateTranslationKey() *PostUpsertBulk {
	return u.Update(func(s *PostUpsert) {
		s.UpdateTranslationKey()
	})
}

// ClearTranslationKey clears the value of the "translation_key" field.
func (u *PostUpsertBulk) ClearTranslationKey() *PostUpsertBulk {
	return u.Update(func(s *PostUpsert) {
		s.ClearTranslationKey()
	})
}

// SetTitle sets the "title" field.
func (u *PostUpsertBulk) SetTitle(v string) *PostUpsertBulk {
	return u.Update(func(s *PostUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *PostUpsertBulk) UpdateTitle() *PostUpsertBulk {
	return u.Update(func(s *PostUpsert) {
		s.UpdateTitle()
	})
}

// SetDescription sets the "description" field.
func (u *PostUpsertBulk) SetDescription(v string) *PostUpsertBulk {
	return u.Update(func(s *PostUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *PostUpsertBulk) UpdateDescription() *PostUpsertBulk {
	return u.Update(func(s *PostUpsert) {
		s.UpdateDescription()
	})
}

// SetContent sets the "content" field.
func (u *PostUpsertBulk) SetContent(v string) *PostUpsertBulk {
	return u.Update(func(s *PostUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *PostUpsertBulk) UpdateContent() *PostUpsertBulk {
	return u.Update(func(s *PostUpsert) {
		s.UpdateContent()
	})
}

// SetTags sets the "tags" field.
func (u *PostUpsertBulk) SetTags(v []string) *PostUpsertBulk {
	return u.Update(func(s *PostUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *PostUpsertBulk) UpdateTags() *PostUpsertBulk {
	return u.Update(func(s *PostUpsert) {
		s.UpdateTags()
	})
}

// SetCoverURL sets the "cover_url" field.
func (u *PostUpsertBulk) SetCoverURL(v string) *PostUpsertBulk {
	return u.Update(func(s *PostUpsert) {
		s.SetCoverURL(v)
	})
}

// UpdateCoverURL sets the "cover_url" field to the value that was provided on create.
func (u *PostUpsertBulk) UpdateCoverURL() *PostUpsertBulk {
	return u.Update(func(s *PostUpsert) {
		s.UpdateCoverURL()
	})
}

// ClearCoverURL clears the value of the "cover_url" field.
func (u *PostUpsertBulk) ClearCoverURL() *PostUpsertBulk {
	return u.Update(func(s *PostUpsert) {
		s.ClearCoverURL()
	})
}

// SetCoverAlt sets the "cover_alt" field.
func (u *PostUpsertBulk) SetCoverAlt(v string) *PostUpsertBulk {
	return u.Update(func(s *PostUpsert) {
		s.SetCoverAlt(v)
	})
}

// UpdateCoverAlt sets the "cover_alt" field to the value that was provided on create.
func (u *PostUpsertBulk) UpdateCoverAlt() *PostUpsertBulk {
	return u.Update(func(s *PostUpsert) {
		s.UpdateCoverAlt()
	})
}

// ClearCoverAlt clears the value of the "cover_alt" field.
func (u *PostUpsertBulk) ClearCoverAlt() *PostUpsertBulk {
	return u.Update(func(s *PostUpsert) {
		s.ClearCoverAlt()
	})
}

// SetPublishedAt sets the "published_at" field.
func (u *PostUpsertBulk) SetPublishedAt(v time.Time) *PostUpsertBulk {
	return u.Update(func(s *PostUpsert) {
		s.SetPublishedAt(v)
	})
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *PostUpsertBulk) UpdatePublishedAt() *PostUpsertBulk {
	return u.Update(func(s *PostUpsert) {
		s.UpdatePublishedAt()
	})
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *PostUpsertBulk) ClearPublishedAt() *PostUpsertBulk {
	return u.Update(func(s *PostUpsert) {
		s.ClearPublishedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PostUpsertBulk) SetUpdatedAt(v time.Time) *PostUpsertBulk {
	return u.Update(func(s *PostUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PostUpsertBulk) UpdateUpdatedAt() *PostUpsertBulk {
	return u.Update(func(s *PostUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPublishedSnapshot sets the "published_snapshot" field.
func (u *PostUpsertBulk) SetPublishedSnapshot(v *model.Snapshot) *PostUpsertBulk {
	return u.Update(func(s *PostUpsert) {
		s.SetPublishedSnapshot(v)
	})
}

// UpdatePublishedSnapshot sets the "published_snapshot" field to the value that was provided on create.
func (u *PostUpsertBulk) UpdatePublishedSnapshot() *PostUpsertBulk {
	return u.Update(func(s *PostUpsert) {
		s.UpdatePublishedSnapshot()
	})
}

// ClearPublishedSnapshot clears the value of the "published_snapshot" field.
func (u *PostUpsertBulk) ClearPublishedSnapshot() *PostUpsertBulk {
	return u.Update(func(s *PostUpsert) {
		s.ClearPublishedSnapshot()
	})
}

// Exec executes the query.
func (u *PostUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PostCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PostCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PostUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
