// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/nachop51/nachop51/ent/post"
	"github.com/nachop51/nachop51/ent/predicate"
	"github.com/nachop51/nachop51/internal/model"
)

// PostUpdate is the builder for updating Post entities.
type PostUpdate struct {
	config
	hooks    []Hook
	mutation *PostMutation
}

// Where appends a list predicates to the PostUpdate builder.
func (_u *PostUpdate) Where(ps ...predicate.Post) *PostUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSlug sets the "slug" field.
func (_u *PostUpdate) SetSlug(v string) *PostUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *PostUpdate) SetNillableSlug(v *string) *PostUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetOldSlugs sets the "old_slugs" field.
func (_u *PostUpdate) SetOldSlugs(v []string) *PostUpdate {
	_u.mutation.SetOldSlugs(v)
	return _u
}

// AppendOldSlugs appends value to the "old_slugs" field.
func (_u *PostUpdate) AppendOldSlugs(v []string) *PostUpdate {
	_u.mutation.AppendOldSlugs(v)
	return _u
}

// SetTranslationKey sets the "translation_key" field.
func (_u *PostUpdate) SetTranslationKey(v string) *PostUpdate {
	_u.mutation.SetTranslationKey(v)
	return _u
}

// SetNillableTranslationKey sets the "translation_key" field if the given value is not nil.
func (_u *PostUpdate) SetNillableTranslationKey(v *string) *PostUpdate {
	if v != nil {
		_u.SetTranslationKey(*v)
	}
	return _u
}

// ClearTranslationKey clears the value of the "translation_key" field.
func (_u *PostUpdate) ClearTranslationKey() *PostUpdate {
	_u.mutation.ClearTranslationKey()
	return _u
}

// SetTitle sets the "title" field.
func (_u *PostUpdate) SetTitle(v string) *PostUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PostUpdate) SetNillableTitle(v *string) *PostUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PostUpdate) SetDescription(v string) *PostUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PostUpdate) SetNillableDescription(v *string) *PostUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *PostUpdate) SetContent(v string) *PostUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *PostUpdate) SetNillableContent(v *string) *PostUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *PostUpdate) SetTags(v []string) *PostUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *PostUpdate) AppendTags(v []string) *PostUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// SetCoverURL sets the "cover_url" field.
func (_u *PostUpdate) SetCoverURL(v string) *PostUpdate {
	_u.mutation.SetCoverURL(v)
	return _u
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (_u *PostUpdate) SetNillableCoverURL(v *string) *PostUpdate {
	if v != nil {
		_u.SetCoverURL(*v)
	}
	return _u
}

// ClearCoverURL clears the value of the "cover_url" field.
func (_u *PostUpdate) ClearCoverURL() *PostUpdate {
	_u.mutation.ClearCoverURL()
	return _u
}

// SetCoverAlt sets the "cover_alt" field.
func (_u *PostUpdate) SetCoverAlt(v string) *PostUpdate {
	_u.mutation.SetCoverAlt(v)
	return _u
}

// SetNillableCoverAlt sets the "cover_alt" field if the given value is not nil.
func (_u *PostUpdate) SetNillableCoverAlt(v *string) *PostUpdate {
	if v != nil {
		_u.SetCoverAlt(*v)
	}
	return _u
}

// ClearCoverAlt clears the value of the "cover_alt" field.
func (_u *PostUpdate) ClearCoverAlt() *PostUpdate {
	_u.mutation.ClearCoverAlt()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *PostUpdate) SetPublishedAt(v time.Time) *PostUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *PostUpdate) SetNillablePublishedAt(v *time.Time) *PostUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *PostUpdate) ClearPublishedAt() *PostUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PostUpdate) SetUpdatedAt(v time.Time) *PostUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPublishedSnapshot sets the "published_snapshot" field.
func (_u *PostUpdate) SetPublishedSnapshot(v *model.Snapshot) *PostUpdate {
	_u.mutation.SetPublishedSnapshot(v)
	return _u
}

// ClearPublishedSnapshot clears the value of the "published_snapshot" field.
func (_u *PostUpdate) ClearPublishedSnapshot() *PostUpdate {
	_u.mutation.ClearPublishedSnapshot()
	return _u
}

// Mutation returns the PostMutation object of the builder.
func (_u *PostUpdate) Mutation() *PostMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PostUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PostUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PostUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := post.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *PostUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(post.Table, post.Columns, sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(post.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.OldSlugs(); ok {
		_spec.SetField(post.FieldOldSlugs, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedOldSlugs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, post.FieldOldSlugs, value)
		})
	}
	if value, ok := _u.mutation.TranslationKey(); ok {
		_spec.SetField(post.FieldTranslationKey, field.TypeString, value)
	}
	if _u.mutation.TranslationKeyCleared() {
		_spec.ClearField(post.FieldTranslationKey, field.TypeString)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(post.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(post.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(post.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(post.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, post.FieldTags, value)
		})
	}
	if value, ok := _u.mutation.CoverURL(); ok {
		_spec.SetField(post.FieldCoverURL, field.TypeString, value)
	}
	if _u.mutation.CoverURLCleared() {
		_spec.ClearField(post.FieldCoverURL, field.TypeString)
	}
	if value, ok := _u.mutation.CoverAlt(); ok {
		_spec.SetField(post.FieldCoverAlt, field.TypeString, value)
	}
	if _u.mutation.CoverAltCleared() {
		_spec.ClearField(post.FieldCoverAlt, field.TypeString)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(post.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(post.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(post.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PublishedSnapshot(); ok {
		_spec.SetField(post.FieldPublishedSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.PublishedSnapshotCleared() {
		_spec.ClearField(post.FieldPublishedSnapshot, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{post.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PostUpdateOne is the builder for updating a single Post entity.
type PostUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PostMutation
}

// SetSlug sets the "slug" field.
func (_u *PostUpdateOne) SetSlug(v string) *PostUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableSlug(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetOldSlugs sets the "old_slugs" field.
func (_u *PostUpdateOne) SetOldSlugs(v []string) *PostUpdateOne {
	_u.mutation.SetOldSlugs(v)
	return _u
}

// AppendOldSlugs appends value to the "old_slugs" field.
func (_u *PostUpdateOne) AppendOldSlugs(v []string) *PostUpdateOne {
	_u.mutation.AppendOldSlugs(v)
	return _u
}

// SetTranslationKey sets the "translation_key" field.
func (_u *PostUpdateOne) SetTranslationKey(v string) *PostUpdateOne {
	_u.mutation.SetTranslationKey(v)
	return _u
}

// SetNillableTranslationKey sets the "translation_key" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableTranslationKey(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetTranslationKey(*v)
	}
	return _u
}

// ClearTranslationKey clears the value of the "translation_key" field.
func (_u *PostUpdateOne) ClearTranslationKey() *PostUpdateOne {
	_u.mutation.ClearTranslationKey()
	return _u
}

// SetTitle sets the "title" field.
func (_u *PostUpdateOne) SetTitle(v string) *PostUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableTitle(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PostUpdateOne) SetDescription(v string) *PostUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableDescription(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *PostUpdateOne) SetContent(v string) *PostUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableContent(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *PostUpdateOne) SetTags(v []string) *PostUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *PostUpdateOne) AppendTags(v []string) *PostUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// SetCoverURL sets the "cover_url" field.
func (_u *PostUpdateOne) SetCoverURL(v string) *PostUpdateOne {
	_u.mutation.SetCoverURL(v)
	return _u
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableCoverURL(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetCoverURL(*v)
	}
	return _u
}

// ClearCoverURL clears the value of the "cover_url" field.
func (_u *PostUpdateOne) ClearCoverURL() *PostUpdateOne {
	_u.mutation.ClearCoverURL()
	return _u
}

// SetCoverAlt sets the "cover_alt" field.
func (_u *PostUpdateOne) SetCoverAlt(v string) *PostUpdateOne {
	_u.mutation.SetCoverAlt(v)
	return _u
}

// SetNillableCoverAlt sets the "cover_alt" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableCoverAlt(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetCoverAlt(*v)
	}
	return _u
}

// ClearCoverAlt clears the value of the "cover_alt" field.
func (_u *PostUpdateOne) ClearCoverAlt() *PostUpdateOne {
	_u.mutation.ClearCoverAlt()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *PostUpdateOne) SetPublishedAt(v time.Time) *PostUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillablePublishedAt(v *time.Time) *PostUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *PostUpdateOne) ClearPublishedAt() *PostUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PostUpdateOne) SetUpdatedAt(v time.Time) *PostUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPublishedSnapshot sets the "published_snapshot" field.
func (_u *PostUpdateOne) SetPublishedSnapshot(v *model.Snapshot) *PostUpdateOne {
	_u.mutation.SetPublishedSnapshot(v)
	return _u
}

// ClearPublishedSnapshot clears the value of the "published_snapshot" field.
func (_u *PostUpdateOne) ClearPublishedSnapshot() *PostUpdateOne {
	_u.mutation.ClearPublishedSnapshot()
	return _u
}

// Mutation returns the PostMutation object of the builder.
func (_u *PostUpdateOne) Mutation() *PostMutation {
	return _u.mutation
}

// Where appends a list predicates to the PostUpdate builder.
func (_u *PostUpdateOne) Where(ps ...predicate.Post) *PostUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PostUpdateOne) Select(field string, fields ...string) *PostUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Post entity.
func (_u *PostUpdateOne) Save(ctx context.Context) (*Post, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostUpdateOne) SaveX(ctx context.Context) *Post {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PostUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PostUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := post.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *PostUpdateOne) sqlSave(ctx context.Context) (_node *Post, err error) {
	_spec := sqlgraph.NewUpdateSpec(post.Table, post.Columns, sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Post.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, post.FieldID)
		for _, f := range fields {
			if !post.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != post.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(post.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.OldSlugs(); ok {
		_spec.SetField(post.FieldOldSlugs, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedOldSlugs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, post.FieldOldSlugs, value)
		})
	}
	if value, ok := _u.mutation.TranslationKey(); ok {
		_spec.SetField(post.FieldTranslationKey, field.TypeString, value)
	}
	if _u.mutation.TranslationKeyCleared() {
		_spec.ClearField(post.FieldTranslationKey, field.TypeString)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(post.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(post.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(post.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(post.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, post.FieldTags, value)
		})
	}
	if value, ok := _u.mutation.CoverURL(); ok {
		_spec.SetField(post.FieldCoverURL, field.TypeString, value)
	}
	if _u.mutation.CoverURLCleared() {
		_spec.ClearField(post.FieldCoverURL, field.TypeString)
	}
	if value, ok := _u.mutation.CoverAlt(); ok {
		_spec.SetField(post.FieldCoverAlt, field.TypeString, value)
	}
	if _u.mutation.CoverAltCleared() {
		_spec.ClearField(post.FieldCoverAlt, field.TypeString)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(post.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(post.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(post.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PublishedSnapshot(); ok {
		_spec.SetField(post.FieldPublishedSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.PublishedSnapshotCleared() {
		_spec.ClearField(post.FieldPublishedSnapshot, field.TypeJSON)
	}
	_node = &Post{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{post.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
