// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/nachop51/nachop51/ent/post"
	"github.com/nachop51/nachop51/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	postFields := schema.Post{}.Fields()
	_ = postFields
	// postDescOldSlugs is the schema descriptor for old_slugs field.
	postDescOldSlugs := postFields[3].Descriptor()
	// post.DefaultOldSlugs holds the default value on creation for the old_slugs field.
	post.DefaultOldSlugs = postDescOldSlugs.Default.([]string)
	// postDescTitle is the schema descriptor for title field.
	postDescTitle := postFields[5].Descriptor()
	// post.DefaultTitle holds the default value on creation for the title field.
	post.DefaultTitle = postDescTitle.Default.(string)
	// postDescDescription is the schema descriptor for description field.
	postDescDescription := postFields[6].Descriptor()
	// post.DefaultDescription holds the default value on creation for the description field.
	post.DefaultDescription = postDescDescription.Default.(string)
	// postDescContent is the schema descriptor for content field.
	postDescContent := postFields[7].Descriptor()
	// post.DefaultContent holds the default value on creation for the content field.
	post.DefaultContent = postDescContent.Default.(string)
	// postDescTags is the schema descriptor for tags field.
	postDescTags := postFields[8].Descriptor()
	// post.DefaultTags holds the default value on creation for the tags field.
	post.DefaultTags = postDescTags.Default.([]string)
	// postDescCreatedAt is the schema descriptor for created_at field.
	postDescCreatedAt := postFields[12].Descriptor()
	// post.DefaultCreatedAt holds the default value on creation for the created_at field.
	post.DefaultCreatedAt = postDescCreatedAt.Default.(func() time.Time)
	// postDescUpdatedAt is the schema descriptor for updated_at field.
	postDescUpdatedAt := postFields[13].Descriptor()
	// post.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	post.DefaultUpdatedAt = postDescUpdatedAt.Default.(func() time.Time)
	// post.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	post.UpdateDefaultUpdatedAt = postDescUpdatedAt.UpdateDefault.(func() time.Time)
	// postDescID is the schema descriptor for id field.
	postDescID := postFields[0].Descriptor()
	// post.DefaultID holds the default value on creation for the id field.
	post.DefaultID = postDescID.Default.(func() uuid.UUID)
}
